### ISSUE TITLE
Feature to list only visible pictures

### ISSUE THREAD

**Issue by rm-medienagentur** [Tastaturberuf/contao-image-copyright-bundle#1]
Nice Plugin! 
Is it possible to list just pictures, which are placed and visible in the frontend pages?

**Comment by Tastaturberuf** [comment]
Thank you.

That is not possible because you can implement images as `content elements`, `html <img>-definitions`, insert tags `{{image::*}}`, `css url() data types` or even in `JavaScript`. 

To reach that goal you must crawl the entire site HTML, all CSS definitions and parse and executed all JavaScript. Thats to much effort for this little result. 

Each image in the database should have a license notice (if it needs one), whether the image is used or not. It doesn't matter if you end up giving hints for images that you don't use. Rather too much from too little and risk a written warning from a lawer.
